// Code generated by MockGen. DO NOT EDIT.
// Source: task_handle.go
//
// Generated by this command:
//
//	mockgen -source=task_handle.go -destination=mock_task_handle_test.go -package=atlasic
//

// Package atlasic is a generated GoMock package.
package atlasic

import (
	context "context"
	reflect "reflect"

	a2a "github.com/mashiike/atlasic/a2a"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskHandle is a mock of TaskHandle interface.
type MockTaskHandle struct {
	ctrl     *gomock.Controller
	recorder *MockTaskHandleMockRecorder
	isgomock struct{}
}

// MockTaskHandleMockRecorder is the mock recorder for MockTaskHandle.
type MockTaskHandleMockRecorder struct {
	mock *MockTaskHandle
}

// NewMockTaskHandle creates a new mock instance.
func NewMockTaskHandle(ctrl *gomock.Controller) *MockTaskHandle {
	mock := &MockTaskHandle{ctrl: ctrl}
	mock.recorder = &MockTaskHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskHandle) EXPECT() *MockTaskHandleMockRecorder {
	return m.recorder
}

// AddMessage mocks base method.
func (m *MockTaskHandle) AddMessage(ctx context.Context, parts []a2a.Part, optFns ...func(*a2a.MessageOptions)) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, parts}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddMessage", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMessage indicates an expected call of AddMessage.
func (mr *MockTaskHandleMockRecorder) AddMessage(ctx, parts any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, parts}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessage", reflect.TypeOf((*MockTaskHandle)(nil).AddMessage), varargs...)
}

// DeleteContextFile mocks base method.
func (m *MockTaskHandle) DeleteContextFile(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContextFile", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContextFile indicates an expected call of DeleteContextFile.
func (mr *MockTaskHandleMockRecorder) DeleteContextFile(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContextFile", reflect.TypeOf((*MockTaskHandle)(nil).DeleteContextFile), ctx, path)
}

// DeleteTaskFile mocks base method.
func (m *MockTaskHandle) DeleteTaskFile(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTaskFile", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTaskFile indicates an expected call of DeleteTaskFile.
func (mr *MockTaskHandleMockRecorder) DeleteTaskFile(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaskFile", reflect.TypeOf((*MockTaskHandle)(nil).DeleteTaskFile), ctx, path)
}

// GetAcceptedOutputModes mocks base method.
func (m *MockTaskHandle) GetAcceptedOutputModes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAcceptedOutputModes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAcceptedOutputModes indicates an expected call of GetAcceptedOutputModes.
func (mr *MockTaskHandleMockRecorder) GetAcceptedOutputModes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAcceptedOutputModes", reflect.TypeOf((*MockTaskHandle)(nil).GetAcceptedOutputModes))
}

// GetContextFile mocks base method.
func (m *MockTaskHandle) GetContextFile(ctx context.Context, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextFile", ctx, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContextFile indicates an expected call of GetContextFile.
func (mr *MockTaskHandleMockRecorder) GetContextFile(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextFile", reflect.TypeOf((*MockTaskHandle)(nil).GetContextFile), ctx, path)
}

// GetContextID mocks base method.
func (m *MockTaskHandle) GetContextID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetContextID indicates an expected call of GetContextID.
func (mr *MockTaskHandleMockRecorder) GetContextID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextID", reflect.TypeOf((*MockTaskHandle)(nil).GetContextID))
}

// GetIncomingMessage mocks base method.
func (m *MockTaskHandle) GetIncomingMessage() a2a.Message {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomingMessage")
	ret0, _ := ret[0].(a2a.Message)
	return ret0
}

// GetIncomingMessage indicates an expected call of GetIncomingMessage.
func (mr *MockTaskHandleMockRecorder) GetIncomingMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomingMessage", reflect.TypeOf((*MockTaskHandle)(nil).GetIncomingMessage))
}

// GetInitialStatus mocks base method.
func (m *MockTaskHandle) GetInitialStatus() a2a.TaskStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInitialStatus")
	ret0, _ := ret[0].(a2a.TaskStatus)
	return ret0
}

// GetInitialStatus indicates an expected call of GetInitialStatus.
func (mr *MockTaskHandleMockRecorder) GetInitialStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInitialStatus", reflect.TypeOf((*MockTaskHandle)(nil).GetInitialStatus))
}

// GetTask mocks base method.
func (m *MockTaskHandle) GetTask(ctx context.Context, historyLength int) (*a2a.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, historyLength)
	ret0, _ := ret[0].(*a2a.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTaskHandleMockRecorder) GetTask(ctx, historyLength any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTaskHandle)(nil).GetTask), ctx, historyLength)
}

// GetTaskFile mocks base method.
func (m *MockTaskHandle) GetTaskFile(ctx context.Context, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskFile", ctx, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskFile indicates an expected call of GetTaskFile.
func (mr *MockTaskHandleMockRecorder) GetTaskFile(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskFile", reflect.TypeOf((*MockTaskHandle)(nil).GetTaskFile), ctx, path)
}

// GetTaskID mocks base method.
func (m *MockTaskHandle) GetTaskID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTaskID indicates an expected call of GetTaskID.
func (mr *MockTaskHandleMockRecorder) GetTaskID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskID", reflect.TypeOf((*MockTaskHandle)(nil).GetTaskID))
}

// ListContextFiles mocks base method.
func (m *MockTaskHandle) ListContextFiles(ctx context.Context, pathPrefix string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContextFiles", ctx, pathPrefix)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContextFiles indicates an expected call of ListContextFiles.
func (mr *MockTaskHandleMockRecorder) ListContextFiles(ctx, pathPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContextFiles", reflect.TypeOf((*MockTaskHandle)(nil).ListContextFiles), ctx, pathPrefix)
}

// ListTaskFiles mocks base method.
func (m *MockTaskHandle) ListTaskFiles(ctx context.Context, pathPrefix string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskFiles", ctx, pathPrefix)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTaskFiles indicates an expected call of ListTaskFiles.
func (mr *MockTaskHandleMockRecorder) ListTaskFiles(ctx, pathPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskFiles", reflect.TypeOf((*MockTaskHandle)(nil).ListTaskFiles), ctx, pathPrefix)
}

// PutContextFile mocks base method.
func (m *MockTaskHandle) PutContextFile(ctx context.Context, path string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutContextFile", ctx, path, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutContextFile indicates an expected call of PutContextFile.
func (mr *MockTaskHandleMockRecorder) PutContextFile(ctx, path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutContextFile", reflect.TypeOf((*MockTaskHandle)(nil).PutContextFile), ctx, path, data)
}

// PutTaskFile mocks base method.
func (m *MockTaskHandle) PutTaskFile(ctx context.Context, path string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutTaskFile", ctx, path, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutTaskFile indicates an expected call of PutTaskFile.
func (mr *MockTaskHandleMockRecorder) PutTaskFile(ctx, path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutTaskFile", reflect.TypeOf((*MockTaskHandle)(nil).PutTaskFile), ctx, path, data)
}

// UpdateStatus mocks base method.
func (m *MockTaskHandle) UpdateStatus(ctx context.Context, state a2a.TaskState, parts []a2a.Part, optFns ...func(*a2a.MessageOptions)) (a2a.TaskStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, state, parts}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateStatus", varargs...)
	ret0, _ := ret[0].(a2a.TaskStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTaskHandleMockRecorder) UpdateStatus(ctx, state, parts any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, state, parts}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTaskHandle)(nil).UpdateStatus), varargs...)
}

// UpsertArtifact mocks base method.
func (m *MockTaskHandle) UpsertArtifact(ctx context.Context, artifact a2a.Artifact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertArtifact", ctx, artifact)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertArtifact indicates an expected call of UpsertArtifact.
func (mr *MockTaskHandleMockRecorder) UpsertArtifact(ctx, artifact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertArtifact", reflect.TypeOf((*MockTaskHandle)(nil).UpsertArtifact), ctx, artifact)
}
