name: Test
on:
  push:
    paths:
      - '**/*.go'
      - '.github/workflows/test.yaml'
      - 'go.mod'
      - 'go.sum'

jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.24"
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - uses: ScribeMD/docker-cache@fb28c93772363301b8d0a6072ce850224b73f74e # v0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('docker-compose.yml') }}
      - name: Start services via docker-compose
        run: docker compose up -d

      - name: Wait for MinIO and ElasticMQ
        run: |
          echo "Waiting for MinIO..."
          for i in {1..10}; do
            curl -f http://localhost:9000/minio/health/live && break || sleep 5
          done
          echo "Waiting for ElasticMQ..."
          for i in {1..10}; do
            curl -f http://localhost:9324/ && break || sleep 5
          done


      - name: Build & Test
        run: |
          go test -race ./...
